# Generated by TrustC Compiler 0.1.0
# Specification Hash: ef146324f68fb20e98d2a653e0ca31ad29690d6ce4a31cc9e11a05ad38502884
from __future__ import annotations

import os
import uuid
from typing import Optional

import jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from db import get_db
from models import User

_raw_jwt_secret = os.environ.get("JWT_SECRET")
if not _raw_jwt_secret or not _raw_jwt_secret.strip():
    raise RuntimeError(
        "Missing required environment secret 'JWT_SECRET'. "
        "Application startup halted."
    )
if _raw_jwt_secret != _raw_jwt_secret.strip():
    raise RuntimeError(
        "Environment secret 'JWT_SECRET' must not contain leading or trailing whitespace. "
        "Application startup halted."
    )
_secret_bytes = _raw_jwt_secret.encode("utf-8")
if len(_raw_jwt_secret.encode("utf-8")) < 32:
    raise RuntimeError(
        "Environment secret 'JWT_SECRET' must be at least 32 bytes for HS256 security. "
        "Application startup halted."
    )
JWT_SECRET: str = _raw_jwt_secret
ALGORITHM = "HS256"
ISSUER = "trustc-local"
AUDIENCE = "trustc-api"

bearer_scheme = HTTPBearer(auto_error=False)


async def get_current_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(bearer_scheme),
    db: AsyncSession = Depends(get_db),
) -> User:
    """Validate Bearer JWT and return authenticated User.

    Enforces fixed HS256 algorithm and required claims (sub, exp, iat, iss, aud).
    Returns sanitized HTTP 401 on any validation failure.
    """
    if credentials is None or not credentials.credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized",
            headers={"WWW-Authenticate": "Bearer"},
        )

    token = credentials.credentials

    try:
        payload = jwt.decode(
            token,
            JWT_SECRET,
            algorithms=[ALGORITHM],
            issuer=ISSUER,
            audience=AUDIENCE,
            options={
                "require": ["sub", "exp", "iat", "iss", "aud"],
                "verify_exp": True,
                "verify_iss": True,
                "verify_aud": True,
            },
        )
        user_id_str = payload.get("sub")
        if not user_id_str:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Unauthorized",
            )
        user_id = uuid.UUID(str(user_id_str))
    except (jwt.PyJWTError, ValueError):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized",
            headers={"WWW-Authenticate": "Bearer"},
        )

    stmt = select(User).where(User.id == user_id)
    result = await db.execute(stmt)
    user = result.scalar_one_or_none()
    if user is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized",
            headers={"WWW-Authenticate": "Bearer"},
        )

    return user
