# Generated by TrustC Compiler 0.1.0
# Specification Hash: ef146324f68fb20e98d2a653e0ca31ad29690d6ce4a31cc9e11a05ad38502884
from __future__ import annotations

import uuid
from typing import Optional

import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column

from db import Base


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    email: Mapped[Optional[str]] = mapped_column(
        sa.String,
        nullable=True,
    )
    password_hash: Mapped[Optional[str]] = mapped_column(
        sa.String,
        nullable=True,
    )


class Trip(Base):
    __tablename__ = "trips"

    id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    destination: Mapped[Optional[str]] = mapped_column(
        sa.String,
        nullable=True,
    )
    # [trustc:provenance kind=owner-set span=11:5-11:13]
    owner_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid(as_uuid=True),
        sa.ForeignKey("users.id"),
        nullable=False,
    )
