# Generated by TrustC Compiler 0.1.0
# Specification Hash: ef146324f68fb20e98d2a653e0ca31ad29690d6ce4a31cc9e11a05ad38502884
from __future__ import annotations

import uuid
from typing import Optional

from pydantic import BaseModel, ConfigDict

# ---------------------------------------------------------------------------
# Request Schemas
# ---------------------------------------------------------------------------


class TripCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    destination: str

# ---------------------------------------------------------------------------
# Response Schemas
# ---------------------------------------------------------------------------


class TripResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    destination: Optional[str] = None
    owner_id: uuid.UUID


class UserIdEmailResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    email: Optional[str] = None
