# Generated by TrustC Compiler 0.1.0
# Specification Hash: ef146324f68fb20e98d2a653e0ca31ad29690d6ce4a31cc9e11a05ad38502884
from __future__ import annotations

import uuid
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from auth import get_current_user
from db import get_db
from models import Trip, User
from schemas import (
    TripCreate,
    TripResponse,
)

router = APIRouter(
    prefix="/trips",
    tags=["trips"],
)


# [trustc:provenance kind=route span=17:1-17:9]
# [trustc:provenance kind=auth span=19:3-19:7]
@router.post(
    "",
    response_model=TripResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_trip(
    payload: TripCreate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Any:
    # [trustc:provenance kind=owner-set span=11:5-11:13]
    item = Trip(
        **payload.model_dump(),
        owner_id=current_user.id,
    )
    db.add(item)
    await db.commit()
    await db.refresh(item)
    return item


# [trustc:provenance kind=route span=23:1-23:9]
# [trustc:provenance kind=auth span=25:3-25:7]
@router.get(
    "/{id}",
    response_model=TripResponse,
)
async def get_trip(
    id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Any:
    # [trustc:provenance kind=query span=23:1-23:9]
    stmt = select(Trip).where(Trip.id == id)
    result = await db.execute(stmt)
    item = result.scalar_one_or_none()
    if item is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Not found",
        )
    # [trustc:provenance kind=owner-check span=11:5-11:13]
    if item.owner_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Forbidden",
        )
    return item
