# Generated by TrustC Compiler 0.1.0
# Specification Hash: ef146324f68fb20e98d2a653e0ca31ad29690d6ce4a31cc9e11a05ad38502884
from __future__ import annotations

import uuid
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from auth import get_current_user
from db import get_db
from models import User
from schemas import (
    UserIdEmailResponse,
)

router = APIRouter(
    prefix="/users",
    tags=["users"],
)


# [trustc:provenance kind=route span=28:1-28:9]
# [trustc:provenance kind=auth span=30:3-30:7]
@router.get(
    "/{id}",
    response_model=UserIdEmailResponse,
)
async def get_user(
    id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Any:
    # [trustc:provenance kind=query span=28:1-28:9]
    stmt = select(User).where(User.id == id)
    result = await db.execute(stmt)
    target_user = result.scalar_one_or_none()
    if target_user is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Not found",
        )
    # [trustc:provenance kind=self-check span=3:5-3:7]
    if current_user.id != id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Forbidden",
        )
    return target_user
